In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [24]:
# Load the DataFrame
df = pd.read_csv('table_EC.csv', header=None)

# Remove the square brackets from the values in the first column
df[1] = df[1].str.replace('[', '').str.replace(']', '')

# Display the modified DataFrame
df.head()

,0,1,2
0,EC_delta_cluster_2_CSZ,"1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...",1.0
1,EC_delta_cluster_2_HE,"1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...",1.0
2,EC_delta_cluster_5_CSZ,"1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...",1.0
3,EC_delta_cluster_5_HE,"1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...",1.0
4,EC_delta_cluster_8_CSZ,"1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...",1.0

In [25]:
# Separate DataFrame based on the condition
df_csz = df[df.iloc[:, 0].str.contains('CSZ', na=False)].iloc[:, [0, 1]]
df_he = df[df.iloc[:, 0].str.contains('HE', na=False)].iloc[:, [0, 1]]

# Display the resulting DataFrames
print("DataFrame with 'CSZ':")
print(df_csz)

print("\nDataFrame with 'HE':")
print(df_he)

DataFrame with 'CSZ':
                         0                                                  1
0   EC_delta_cluster_2_CSZ  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
2   EC_delta_cluster_5_CSZ  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
4   EC_delta_cluster_8_CSZ  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
6   EC_theta_cluster_2_CSZ  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
8   EC_theta_cluster_5_CSZ  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
10  EC_theta_cluster_8_CSZ  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
12  EC_alpha_cluster_2_CSZ  0.95, 0.9666666666666667, 0.9916666666666667, ...
14  EC_alpha_cluster_5_CSZ  1.0, 0.9666666666666667, 0.9583333333333334, 1...
16  EC_alpha_cluster_8_CSZ  1.0, 0.95, 1.0, 0.9916666666666667, 0.99166666...

DataFrame with 'HE':
                        0                                                  1
1   EC_delta_cluster_2_HE  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
3   EC_delta_cluster_5_HE  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
5   EC_delta_cluster_8_HE  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
7   EC_theta_cluster_2_HE  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
9   EC_theta_cluster_5_HE  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
11  EC_theta_cluster_8_HE  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
13  EC_alpha_cluster_2_HE  0.975, 0.9916666666666667, 1.0, 0.991666666666...
15  EC_alpha_cluster_5_HE  1.0, 1.0, 1.0, 0.9833333333333333, 0.983333333...
17  EC_alpha_cluster_8_HE  1.0, 1.0, 0.9915966386554622, 1.0, 1.0, 1.0, 0...

In [26]:
# Split the comma-separated values in the first column into separate columns
df_csz_split = df_csz[1].str.split(',', expand=True)
df_he_split = df_he[1].str.split(',', expand=True)

# Add the second column back to the split DataFrames
df_csz_split.insert(0, 'Type of Cluster and Band', df_csz[0])
df_he_split.insert(0, 'Type of Cluster and Band', df_he[0])

# Rename the columns
df_csz_split.columns = ['Type of Cluster and Band'] + [f'Patient {i}' for i in range(1, df_csz_split.shape[1])]
df_he_split.columns = ['Type of Cluster and Band'] + [f'Patient {i}' for i in range(1, df_he_split.shape[1])]

In [27]:
df_csz_split.head()

,Type of Cluster and Band,Patient 1,Patient 2,Patient 3,Patient 4,Patient 5,Patient 6,Patient 7,Patient 8,Patient 9,...,Patient 14,Patient 15,Patient 16,Patient 17,Patient 18,Patient 19,Patient 20,Patient 21,Patient 22,Patient 23
0,EC_delta_cluster_2_CSZ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,EC_delta_cluster_5_CSZ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,EC_delta_cluster_8_CSZ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
6,EC_theta_cluster_2_CSZ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
8,EC_theta_cluster_5_CSZ,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [28]:
df_he_split.head()

,Type of Cluster and Band,Patient 1,Patient 2,Patient 3,Patient 4,Patient 5,Patient 6,Patient 7,Patient 8,Patient 9,...,Patient 31,Patient 32,Patient 33,Patient 34,Patient 35,Patient 36,Patient 37,Patient 38,Patient 39,Patient 40
1,EC_delta_cluster_2_HE,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,EC_delta_cluster_5_HE,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5,EC_delta_cluster_8_HE,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
7,EC_theta_cluster_2_HE,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
9,EC_theta_cluster_5_HE,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [31]:
# Add a 'Group' column to each DataFrame
df_csz_split['Group'] = 'CSZ'
df_he_split['Group'] = 'HE'

# Combine the two DataFrames
combined_df = pd.concat([df_csz_split, df_he_split], ignore_index=True)

# Melt the combined DataFrame to have a long format
melted_df = combined_df.melt(id_vars=['Type of Cluster and Band', 'Group'], var_name='Patient', value_name='Value')

# Convert the 'Value' column to numeric, coercing errors to NaN
melted_df['Value'] = pd.to_numeric(melted_df['Value'], errors='coerce')

# Drop rows with NaN values in the 'Value' column
melted_df = melted_df.dropna(subset=['Value'])

# Perform ANOVA
model = ols('Value ~ C(Group)', data=melted_df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

# Display the ANOVA table
print(anova_table)

            sum_sq     df          F    PR(>F)
C(Group)  0.002991    1.0  10.378156  0.001349
Residual  0.162828  565.0        NaN       NaN